### ISSUE TITLE
Create User controller (servlet)

### ISSUE THREAD

**Issue by aNieto92** [Xelit3/GamersCreed#4]
Create controler (servlet)

**Comment by aNieto92** [comment]
UserServlet created, and ready for add user, login (create session), check username, logout and check open session, only need to implement the methods of the DB, and test the controller

**Comment by aNieto92** [comment]
Bug in addUser().-> userDAO.crate() crashes when creating user with role

**Comment by aNieto92** [comment]
Fixed bug, and tested  user creation, login, check session and add post.
Soon get All post

**Comment by Xelit3** [comment]
Created method to get all data for the profile

**Comment by aNieto92** [comment]
Get All posts complete, and tested,
User Controller complete
